### ISSUE TITLE
100% false positives

### ISSUE THREAD

**Issue by fsdevblog** [crystal-community/bloom_filter#5]
Did you tested `bloom_filter` in a large database?
```
icr(0.24.1) > bloom = BloomFilter.new_optimal(300_000_000, 1.0e-6); nil
 => nil
icr(0.24.1) > bloom.bytesize
 => 1078319068_u32
icr(0.24.1) > bloom.hash_num
 => 20_u8
```
when I insert about 15-20 millions records, i receive 100% false positive.
based on https://hur.st/bloomfilter - settings from `.new_optimal` are correct.

**Comment by greyblake** [comment]
Interesting... Looks like the formula does not work correctly for small probability of false positives.
Also 0.0001% does not look like real expectation from BloomFilter. You should try something more realistic like 1-2%: `0.01`

**Comment by fsdevblog** [comment]
@greyblake 
Дык, ожидаемый FPP напрямую влияет на кол-во хешей. Чем больше хешей, тем меньше вероятность впоймать ложно-позитивный детект. Я сейчас эксперементирую с разными настройками, чуть позже сообщу что вышло.

-----
for english speaking readers:

The expected FPP directly affects the number of hashes. The more hashes, the less likely to capture a false positive positivity. I'm now experimenting with different settings, a little later I'll let you know what happened.

**Comment by fsdevblog** [comment]
@greyblake
ты оказался чертовски прав. Неспроста я мало что понимаю в математике. Поставил 0.01% и по факту, в базе на 300_000_000 записей (заполнено 213 миллионов) FPP равен 0.1930%. Это вполне приемлемо. Спасибо.

------

you were damn right. Setting 0.01% FPP and in fact, in the database for 300_000_000 records (213 million filled) FPP is equal to 0.1930%. This is perfectly acceptable. Thank you.

**Comment by greyblake** [comment]
> The more hashes, the less likely to capture a false positive positivity.

It's not always like this. You should also consider the size. Having too many hashes my result into having almost all bits set to `1`, which results high percentage of false positives.
